### ISSUE TITLE
cannot open svg from histogram (distogram) in windows or mac

### ISSUE THREAD

**Issue by grandrea** [Rappsilber-Laboratory/build-xiview#105] opened 2024-05-20 10:29 UTC
Hello,

Downloading .svg and trying to open in inkscape causes crash of inkscape in windows or mac, but i can open it in linux. File attached. Thanks!!

![histogram](https://github.com/Rappsilber-Laboratory/build-xiview/assets/44289027/90e7445b-f50c-46fb-b900-c0f08b174871)

**Comment by colin-combe** [comment] 2024-05-20 13:31
its a duplicate of https://github.com/Rappsilber-Laboratory/issue-tracker/issues/550 in the private issue tracker
i tried to transfer that issue here (it had no sensitive info in it) but it turns out you can't transfer an issue from private project to a public one.

Every thing that was said there applies here:
- its an InkScape bug https://gitlab.com/inkscape/inbox/-/issues/6833
- fix is to remove `.distoDiv .c3-axis.c3-axis-x .tick:nth-of-type(10n+1) line { transform: scaleY(1.2); }` (probably line 10)
- it's open issue on my todo list to remove that line before export because InkScape don't seem to be fixing

**Comment by colin-combe** [comment] 2024-06-12 08:17
> it's open issue on my todo list to remove that line before export because InkScape don't seem to be fixing

@grandrea - ok, that workaround should be there in v1.0.5, now deployed at xiview.org

**Closed by colin-combe** 2024-06-12 08:17 UTC
